import { WarrantyClaim } from './types';

export const MOCK_RESIDENCIALES = [
  { id: '1', name: 'Arcos Santa Maria I' },
  { id: '2', name: 'Arcos Santa Maria II' },
  { id: '3', name: 'Villa del Sol' },
  { id: '4', name: 'Las Colinas' },
  { id: '5', name: 'Jardines del Norte' },
  { id: '6', name: 'Costa Verde' },
];

export const MOCK_UNITS_BY_RESIDENCIAL: Record<string, string[]> = {
  '1': ['Apto 101', 'Apto 102', 'Apto 103', 'Apto 201', 'Apto 202', 'Apto 203'],
  '2': ['Apto 204', 'Apto 205', 'Apto 301', 'Apto 302', 'Apto 303', 'Apto 304'],
  '3': ['Casa 12', 'Casa 13', 'Casa 14', 'Casa 15', 'Casa 16', 'Casa 17', 'Casa 18'],
  '4': ['Lote 8', 'Lote 9', 'Lote 10', 'Apto 401', 'Apto 402', 'Apto 403'],
  '5': ['Apto 501', 'Apto 502', 'Apto 503', 'Apto 601', 'Apto 602', 'Apto 603'],
  '6': ['Apto 601', 'Apto 602', 'Apto 701', 'Apto 702', 'Apto 801', 'Apto 802'],
};

export const MOCK_RESIDENTS = [
  { id: 'res1', name: 'Juan Pérez García', phone: '6621-1234' },
  { id: 'res2', name: 'María González López', phone: '6621-5678' },
  { id: 'res3', name: 'Carlos López Ramírez', phone: '6622-9012' },
  { id: 'res4', name: 'Ana Martínez Sánchez', phone: '6622-3456' },
  { id: 'res5', name: 'Luis Rodríguez Castro', phone: '6623-7890' },
  { id: 'res6', name: 'Sofia Hernández Morales', phone: '6623-1234' },
  { id: 'res7', name: 'Pedro Sánchez Torres', phone: '6624-5678' },
  { id: 'res8', name: 'Laura Flores Ruiz', phone: '6624-9012' },
  { id: 'res9', name: 'Miguel Ramírez Díaz', phone: '6625-3456' },
  { id: 'res10', name: 'Carmen Flores Vega', phone: '6625-7890' },
];

export const MOCK_WARRANTY_CLAIMS: WarrantyClaim[] = [
  {
    id: 'war1',
    claimNumber: 'GAR-2024-001',
    residencialId: '1',
    residencialName: 'Arcos Santa Maria I',
    unitNumber: 'Apto 101',
    residentId: 'res1',
    residentName: 'Juan Pérez García',
    residentPhone: '6621-1234',
    claims: [
      {
        id: 'claim1',
        claimType: 'leak',
        location: 'master_bathroom',
        description: 'Fuga de agua debajo del lavabo del baño principal. El agua se acumula constantemente.',
        files: [
          {
            id: 'file1',
            name: 'fuga_lavabo.jpg',
            url: '/mock/fuga_lavabo.jpg',
            type: 'image',
            uploadedAt: new Date(2024, 10, 10, 8, 30).toISOString(),
          },
          {
            id: 'file2',
            name: 'fuga_video.mp4',
            url: '/mock/fuga_video.mp4',
            type: 'video',
            uploadedAt: new Date(2024, 10, 10, 8, 35).toISOString(),
          },
        ],
      },
      {
        id: 'claim2',
        claimType: 'door',
        location: 'master_bedroom',
        description: 'La puerta de la recámara principal no cierra correctamente, tiene roce con el marco.',
        files: [],
      },
    ],
    status: 'in_progress',
    priority: 'high',
    submittedAt: new Date(2024, 10, 10, 8, 45).toISOString(),
    reviewedAt: new Date(2024, 10, 11, 10, 0).toISOString(),
    reviewedBy: 'Admin Residencial',
    adminNotes: 'Programada visita técnica para el 25/11/2024',
    estimatedCompletionDate: new Date(2024, 10, 25).toISOString(),
  },
  {
    id: 'war2',
    claimNumber: 'GAR-2024-002',
    residencialId: '3',
    residencialName: 'Villa del Sol',
    unitNumber: 'Casa 12',
    residentId: 'res5',
    residentName: 'Luis Rodríguez Castro',
    residentPhone: '6623-7890',
    claims: [
      {
        id: 'claim3',
        claimType: 'electrical',
        location: 'living_room',
        description: 'Dos contactos de la sala no funcionan correctamente.',
        files: [
          {
            id: 'file3',
            name: 'contactos.jpg',
            url: '/mock/contactos.jpg',
            type: 'image',
            uploadedAt: new Date(2024, 10, 12, 15, 20).toISOString(),
          },
        ],
      },
    ],
    status: 'approved',
    priority: 'medium',
    submittedAt: new Date(2024, 10, 12, 15, 30).toISOString(),
    reviewedAt: new Date(2024, 10, 13, 9, 0).toISOString(),
    reviewedBy: 'Admin Residencial',
    adminNotes: 'Aprobada. Electricista asignado.',
    estimatedCompletionDate: new Date(2024, 10, 20).toISOString(),
  },
  {
    id: 'war3',
    claimNumber: 'GAR-2024-003',
    residencialId: '2',
    residencialName: 'Arcos Santa Maria II',
    unitNumber: 'Apto 205',
    residentId: 'res3',
    residentName: 'Carlos López Ramírez',
    residentPhone: '6622-9012',
    claims: [
      {
        id: 'claim4',
        claimType: 'floor',
        location: 'kitchen',
        description: 'Loseta suelta en la cocina, se mueve al caminar sobre ella.',
        files: [],
      },
      {
        id: 'claim5',
        claimType: 'paint',
        location: 'living_room',
        description: 'Pintura descascarada en pared de la sala.',
        files: [
          {
            id: 'file4',
            name: 'pintura_sala.jpg',
            url: '/mock/pintura_sala.jpg',
            type: 'image',
            uploadedAt: new Date(2024, 10, 15, 11, 0).toISOString(),
          },
        ],
      },
      {
        id: 'claim6',
        claimType: 'window',
        location: 'secondary_bedroom_1',
        description: 'Ventana de recámara secundaria no abre correctamente.',
        files: [],
      },
    ],
    status: 'in_review',
    priority: 'medium',
    submittedAt: new Date(2024, 10, 15, 11, 15).toISOString(),
  },
  {
    id: 'war4',
    claimNumber: 'GAR-2024-004',
    residencialId: '1',
    residencialName: 'Arcos Santa Maria I',
    unitNumber: 'Apto 202',
    residentId: 'res2',
    residentName: 'María González López',
    residentPhone: '6621-5678',
    claims: [
      {
        id: 'claim7',
        claimType: 'humidity',
        location: 'secondary_bathroom',
        description: 'Humedad en el techo del baño secundario, se observan manchas.',
        files: [
          {
            id: 'file5',
            name: 'humedad_techo.jpg',
            url: '/mock/humedad_techo.jpg',
            type: 'image',
            uploadedAt: new Date(2024, 10, 18, 14, 0).toISOString(),
          },
          {
            id: 'file6',
            name: 'humedad_detalle.jpg',
            url: '/mock/humedad_detalle.jpg',
            type: 'image',
            uploadedAt: new Date(2024, 10, 18, 14, 2).toISOString(),
          },
        ],
      },
    ],
    status: 'pending',
    priority: 'high',
    submittedAt: new Date(2024, 10, 18, 14, 10).toISOString(),
  },
  {
    id: 'war5',
    claimNumber: 'GAR-2024-005',
    residencialId: '5',
    residencialName: 'Jardines del Norte',
    unitNumber: 'Apto 501',
    residentId: 'res6',
    residentName: 'Sofia Hernández Morales',
    residentPhone: '6623-1234',
    claims: [
      {
        id: 'claim8',
        claimType: 'water_pressure',
        location: 'master_bathroom',
        description: 'Presión de agua muy baja en regadera del baño principal.',
        files: [],
      },
    ],
    status: 'resolved',
    priority: 'low',
    submittedAt: new Date(2024, 10, 5, 9, 0).toISOString(),
    reviewedAt: new Date(2024, 10, 6, 10, 0).toISOString(),
    resolvedAt: new Date(2024, 10, 8, 16, 30).toISOString(),
    reviewedBy: 'Admin Residencial',
    adminNotes: 'Resuelta. Se limpió filtro de regadera.',
  },
];
