import { WarrantyClaim } from './types';

export const MOCK_RESIDENCIALES = [
  { id: '1', name: 'Arcos Santa Maria I' },
  { id: '2', name: 'Arcos Santa Maria II' },
  { id: '3', name: 'Villa del Sol' },
  { id: '4', name: 'Las Colinas' },
  { id: '5', name: 'Jardines del Norte' },
];

export const MOCK_UNITS_BY_RESIDENCIAL: Record<string, string[]> = {
  '1': ['Apto 101', 'Apto 102', 'Apto 103', 'Apto 201', 'Apto 202', 'Apto 203'],
  '2': ['Apto 204', 'Apto 205', 'Apto 301', 'Apto 302', 'Apto 303', 'Apto 304'],
  '3': ['Casa 12', 'Casa 13', 'Casa 14', 'Casa 15', 'Casa 16', 'Casa 17'],
  '4': ['Lote 8', 'Lote 9', 'Lote 10', 'Apto 401', 'Apto 402', 'Apto 403'],
  '5': ['Apto 501', 'Apto 502', 'Apto 503', 'Apto 601', 'Apto 602', 'Apto 603'],
};

export const MOCK_RESIDENTS = [
  { id: 'res1', name: 'Juan Pérez García', phone: '6621-1234' },
  { id: 'res2', name: 'María González López', phone: '6621-5678' },
  { id: 'res3', name: 'Carlos López Ramírez', phone: '6622-9012' },
  { id: 'res4', name: 'Ana Martínez Sánchez', phone: '6622-3456' },
  { id: 'res5', name: 'Luis Rodríguez Castro', phone: '6623-7890' },
  { id: 'res6', name: 'Sofia Hernández Morales', phone: '6623-1234' },
  { id: 'res7', name: 'Pedro Sánchez Torres', phone: '6624-5678' },
  { id: 'res8', name: 'Laura Flores Ruiz', phone: '6624-9012' },
];

export const MOCK_WARRANTY_CLAIMS: WarrantyClaim[] = [
  {
    id: 'war1',
    claimNumber: 'GAR-2024-001',
    residencialId: '1',
    residencialName: 'Arcos Santa Maria I',
    unitNumber: 'Apto 101',
    residentId: 'res1',
    residentName: 'Juan Pérez García',
    residentPhone: '6621-1234',
    claims: [
      {
        id: 'claim1',
        claimType: 'leak',
        location: 'master_bathroom',
        description: 'Fuga de agua debajo del lavabo del baño principal.',
        files: [],
      },
      {
        id: 'claim2',
        claimType: 'door',
        location: 'master_bedroom',
        description: 'La puerta no cierra correctamente.',
        files: [],
      },
    ],
    status: 'pending',
    priority: 'high',
    submittedAt: new Date(2024, 10, 22, 9, 0).toISOString(),
    statusHistory: [
      {
        id: 'h1',
        status: 'pending',
        timestamp: new Date(2024, 10, 22, 9, 0).toISOString(),
        changedBy: 'Sistema',
        notes: 'Reclamo creado',
      },
    ],
  },
  {
    id: 'war2',
    claimNumber: 'GAR-2024-002',
    residencialId: '3',
    residencialName: 'Villa del Sol',
    unitNumber: 'Casa 12',
    residentId: 'res5',
    residentName: 'Luis Rodríguez Castro',
    residentPhone: '6623-7890',
    claims: [
      {
        id: 'claim3',
        claimType: 'electrical',
        location: 'living_room',
        description: 'Dos contactos no funcionan.',
        files: [],
      },
    ],
    status: 'in_progress',
    priority: 'medium',
    submittedAt: new Date(2024, 10, 18, 14, 0).toISOString(),
    reviewedAt: new Date(2024, 10, 19, 10, 0).toISOString(),
    reviewedBy: 'Ana Martínez - Experiencia Cliente',
    assignedTeam: 'operations',
    scheduledVisitDate: new Date(2024, 10, 25).toISOString(),
    adminNotes: 'Electricista asignado',
    statusHistory: [
      {
        id: 'h2',
        status: 'pending',
        timestamp: new Date(2024, 10, 18, 14, 0).toISOString(),
        changedBy: 'Sistema',
      },
      {
        id: 'h3',
        status: 'approved',
        timestamp: new Date(2024, 10, 19, 10, 0).toISOString(),
        changedBy: 'Ana Martínez',
        notes: 'Aprobado. Asignado a equipo de operaciones.',
      },
      {
        id: 'h4',
        status: 'in_progress',
        timestamp: new Date(2024, 10, 20, 8, 30).toISOString(),
        changedBy: 'Equipo Operaciones',
        notes: 'Iniciado trabajo en sitio',
      },
    ],
  },
  {
    id: 'war3',
    claimNumber: 'GAR-2024-003',
    residencialId: '2',
    residencialName: 'Arcos Santa Maria II',
    unitNumber: 'Apto 205',
    residentId: 'res3',
    residentName: 'Carlos López Ramírez',
    residentPhone: '6622-9012',
    claims: [
      {
        id: 'claim4',
        claimType: 'floor',
        location: 'kitchen',
        description: 'Loseta suelta en la cocina.',
        files: [],
      },
    ],
    status: 'pending',
    priority: 'low',
    submittedAt: new Date(2024, 10, 21, 16, 0).toISOString(),
    statusHistory: [
      {
        id: 'h5',
        status: 'pending',
        timestamp: new Date(2024, 10, 21, 16, 0).toISOString(),
        changedBy: 'Sistema',
      },
    ],
  },
  {
    id: 'war4',
    claimNumber: 'GAR-2024-004',
    residencialId: '1',
    residencialName: 'Arcos Santa Maria I',
    unitNumber: 'Apto 202',
    residentId: 'res2',
    residentName: 'María González López',
    residentPhone: '6621-5678',
    claims: [
      {
        id: 'claim5',
        claimType: 'humidity',
        location: 'secondary_bathroom',
        description: 'Humedad en el techo del baño.',
        files: [],
      },
    ],
    status: 'rejected',
    priority: 'medium',
    submittedAt: new Date(2024, 10, 15, 11, 0).toISOString(),
    reviewedAt: new Date(2024, 10, 16, 9, 0).toISOString(),
    reviewedBy: 'Pedro García - Experiencia Cliente',
    rejectionReason: 'normal_wear',
    rejectionNotes: 'La humedad es resultado del uso normal y no está cubierta por la garantía de construcción.',
    statusHistory: [
      {
        id: 'h6',
        status: 'pending',
        timestamp: new Date(2024, 10, 15, 11, 0).toISOString(),
        changedBy: 'Sistema',
      },
      {
        id: 'h7',
        status: 'rejected',
        timestamp: new Date(2024, 10, 16, 9, 0).toISOString(),
        changedBy: 'Pedro García',
        notes: 'Rechazado por desgaste normal',
      },
    ],
  },
  {
    id: 'war5',
    claimNumber: 'GAR-2024-005',
    residencialId: '5',
    residencialName: 'Jardines del Norte',
    unitNumber: 'Apto 501',
    residentId: 'res6',
    residentName: 'Sofia Hernández Morales',
    residentPhone: '6623-1234',
    claims: [
      {
        id: 'claim6',
        claimType: 'water_pressure',
        location: 'master_bathroom',
        description: 'Presión de agua muy baja.',
        files: [],
        resolutionStatus: 'compliant',
        resolutionNotes: 'Se limpió filtro de regadera. Presión normalizada.',
      },
    ],
    status: 'resolved',
    priority: 'low',
    submittedAt: new Date(2024, 10, 10, 9, 0).toISOString(),
    reviewedAt: new Date(2024, 10, 11, 10, 0).toISOString(),
    resolvedAt: new Date(2024, 10, 14, 15, 30).toISOString(),
    reviewedBy: 'Laura Méndez - Experiencia Cliente',
    assignedTeam: 'finishing',
    scheduledVisitDate: new Date(2024, 10, 14).toISOString(),
    signature: 'data:image/png;base64,mock-signature',
    statusHistory: [
      {
        id: 'h8',
        status: 'pending',
        timestamp: new Date(2024, 10, 10, 9, 0).toISOString(),
        changedBy: 'Sistema',
      },
      {
        id: 'h9',
        status: 'approved',
        timestamp: new Date(2024, 10, 11, 10, 0).toISOString(),
        changedBy: 'Laura Méndez',
        notes: 'Aprobado y asignado a acabados',
      },
      {
        id: 'h10',
        status: 'in_progress',
        timestamp: new Date(2024, 10, 14, 9, 0).toISOString(),
        changedBy: 'Equipo Acabados',
      },
      {
        id: 'h11',
        status: 'resolved',
        timestamp: new Date(2024, 10, 14, 15, 30).toISOString(),
        changedBy: 'Equipo Acabados',
        notes: 'Problema resuelto satisfactoriamente',
      },
    ],
  },
];
