import { CommonSpace, CalendarReservation } from './calendarTypes';
import { Resident } from './ResidentSearch';

export const COMMON_SPACES: CommonSpace[] = [
  {
    id: 'space-1',
    name: 'Salón Social',
    description: 'Amplio salón para eventos y reuniones',
    capacity: 50,
    color: '#3B82F6',
    availableHours: { start: '08:00', end: '22:00' },
  },
  {
    id: 'space-2',
    name: 'Área de BBQ',
    description: 'Zona de parrillas con mesas',
    capacity: 30,
    color: '#EF4444',
    availableHours: { start: '10:00', end: '20:00' },
  },
  {
    id: 'space-3',
    name: 'Gimnasio',
    description: 'Gimnasio equipado',
    capacity: 15,
    color: '#10B981',
    availableHours: { start: '06:00', end: '22:00' },
  },
  {
    id: 'space-4',
    name: 'Piscina',
    description: 'Área de piscina',
    capacity: 40,
    color: '#06B6D4',
    availableHours: { start: '08:00', end: '20:00' },
  },
  {
    id: 'space-5',
    name: 'Cancha de Tenis',
    description: 'Cancha de tenis profesional',
    capacity: 4,
    color: '#F59E0B',
    availableHours: { start: '07:00', end: '21:00' },
  },
];

const now = new Date();
const currentYear = now.getFullYear();
const currentMonth = now.getMonth();

export const MOCK_RESERVATIONS: CalendarReservation[] = [
  {
    id: 'res-1',
    spaceId: 'space-1',
    spaceName: 'Salón Social',
    residentName: 'María García',
    startTime: new Date(currentYear, currentMonth, 24, 18, 0),
    endTime: new Date(currentYear, currentMonth, 24, 23, 0),
    status: 'approved',
    notes: 'Celebración familiar',
  },
  {
    id: 'res-2',
    spaceId: 'space-2',
    spaceName: 'Área de BBQ',
    residentName: 'Juan Pérez',
    startTime: new Date(currentYear, currentMonth, 24, 13, 0),
    endTime: new Date(currentYear, currentMonth, 24, 17, 0),
    status: 'approved',
    notes: 'Almuerzo familiar',
  },
  {
    id: 'res-3',
    spaceId: 'space-3',
    spaceName: 'Gimnasio',
    residentName: 'Carlos López',
    startTime: new Date(currentYear, currentMonth, 24, 7, 0),
    endTime: new Date(currentYear, currentMonth, 24, 9, 0),
    status: 'approved',
    notes: 'Clase de yoga',
  },
  {
    id: 'res-4',
    spaceId: 'space-1',
    spaceName: 'Salón Social',
    residentName: 'Ana Martínez',
    startTime: new Date(currentYear, currentMonth, 25, 19, 0),
    endTime: new Date(currentYear, currentMonth, 25, 22, 0),
    status: 'pending',
    notes: 'Reunión de vecinos',
  },
  {
    id: 'res-5',
    spaceId: 'space-4',
    spaceName: 'Piscina',
    residentName: 'Luis Rodríguez',
    startTime: new Date(currentYear, currentMonth, 26, 10, 0),
    endTime: new Date(currentYear, currentMonth, 26, 13, 0),
    status: 'approved',
    notes: 'Fiesta de cumpleaños infantil',
  },
  {
    id: 'res-6',
    spaceId: 'space-2',
    spaceName: 'Área de BBQ',
    residentName: 'Sofia Hernández',
    startTime: new Date(currentYear, currentMonth, 27, 14, 0),
    endTime: new Date(currentYear, currentMonth, 27, 18, 0),
    status: 'approved',
  },
  {
    id: 'res-7',
    spaceId: 'space-5',
    spaceName: 'Cancha de Tenis',
    residentName: 'Pedro Sánchez',
    startTime: new Date(currentYear, currentMonth, 24, 16, 0),
    endTime: new Date(currentYear, currentMonth, 24, 18, 0),
    status: 'approved',
    notes: 'Partido amistoso',
  },
  {
    id: 'res-8',
    spaceId: 'space-3',
    spaceName: 'Gimnasio',
    residentName: 'Laura Torres',
    startTime: new Date(currentYear, currentMonth, 25, 18, 0),
    endTime: new Date(currentYear, currentMonth, 25, 20, 0),
    status: 'approved',
    notes: 'Entrenamiento personal',
  },
  {
    id: 'res-9',
    spaceId: 'space-1',
    spaceName: 'Salón Social',
    residentName: 'Miguel Ramírez',
    startTime: new Date(currentYear, currentMonth, 28, 20, 0),
    endTime: new Date(currentYear, currentMonth, 28, 23, 0),
    status: 'pending',
    notes: 'Evento corporativo',
  },
  {
    id: 'res-10',
    spaceId: 'space-4',
    spaceName: 'Piscina',
    residentName: 'Carmen Flores',
    startTime: new Date(currentYear, currentMonth, 29, 15, 0),
    endTime: new Date(currentYear, currentMonth, 29, 18, 0),
    status: 'approved',
  },
  {
    id: 'res-11',
    spaceId: 'space-2',
    spaceName: 'Área de BBQ',
    residentName: 'Roberto Castro',
    startTime: new Date(currentYear, currentMonth, 30, 12, 0),
    endTime: new Date(currentYear, currentMonth, 30, 16, 0),
    status: 'approved',
    notes: 'Parrillada familiar',
  },
  {
    id: 'res-12',
    spaceId: 'space-5',
    spaceName: 'Cancha de Tenis',
    residentName: 'Patricia Morales',
    startTime: new Date(currentYear, currentMonth, 25, 9, 0),
    endTime: new Date(currentYear, currentMonth, 25, 11, 0),
    status: 'approved',
    notes: 'Clases de tenis',
  },
  {
    id: 'res-13',
    spaceId: 'space-1',
    spaceName: 'Salón Social',
    residentName: 'Fernando García',
    startTime: new Date(currentYear, currentMonth, 24, 10, 0),
    endTime: new Date(currentYear, currentMonth, 24, 14, 0),
    status: 'approved',
    notes: 'Reunión de negocios',
  },
  {
    id: 'res-14',
    spaceId: 'space-2',
    spaceName: 'Área de BBQ',
    residentName: 'Valeria López',
    startTime: new Date(currentYear, currentMonth, 24, 18, 0),
    endTime: new Date(currentYear, currentMonth, 24, 21, 0),
    status: 'approved',
    notes: 'Cena familiar',
  },
  {
    id: 'res-15',
    spaceId: 'space-3',
    spaceName: 'Gimnasio',
    residentName: 'Diego Martínez',
    startTime: new Date(currentYear, currentMonth, 24, 15, 0),
    endTime: new Date(currentYear, currentMonth, 24, 17, 0),
    status: 'approved',
  },
  {
    id: 'res-16',
    spaceId: 'space-4',
    spaceName: 'Piscina',
    residentName: 'Ana Martínez',
    startTime: new Date(currentYear, currentMonth, 24, 14, 0),
    endTime: new Date(currentYear, currentMonth, 24, 18, 0),
    status: 'approved',
    notes: 'Fiesta infantil',
  },
  {
    id: 'res-17',
    spaceId: 'space-5',
    spaceName: 'Cancha de Tenis',
    residentName: 'Luis Rodríguez',
    startTime: new Date(currentYear, currentMonth, 24, 8, 0),
    endTime: new Date(currentYear, currentMonth, 24, 10, 0),
    status: 'approved',
  },
  {
    id: 'res-18',
    spaceId: 'space-1',
    spaceName: 'Salón Social',
    residentName: 'Sofia Hernández',
    startTime: new Date(currentYear, currentMonth, 26, 16, 0),
    endTime: new Date(currentYear, currentMonth, 26, 20, 0),
    status: 'pending',
    notes: 'Cumpleaños',
  },
  {
    id: 'res-19',
    spaceId: 'space-2',
    spaceName: 'Área de BBQ',
    residentName: 'Pedro Sánchez',
    startTime: new Date(currentYear, currentMonth, 25, 11, 0),
    endTime: new Date(currentYear, currentMonth, 25, 15, 0),
    status: 'approved',
  },
  {
    id: 'res-20',
    spaceId: 'space-3',
    spaceName: 'Gimnasio',
    residentName: 'Carmen Flores',
    startTime: new Date(currentYear, currentMonth, 26, 6, 0),
    endTime: new Date(currentYear, currentMonth, 26, 8, 0),
    status: 'approved',
    notes: 'Clase de spinning',
  },
  {
    id: 'res-21',
    spaceId: 'space-4',
    spaceName: 'Piscina',
    residentName: 'Roberto Castro',
    startTime: new Date(currentYear, currentMonth, 27, 9, 0),
    endTime: new Date(currentYear, currentMonth, 27, 12, 0),
    status: 'approved',
  },
  {
    id: 'res-22',
    spaceId: 'space-5',
    spaceName: 'Cancha de Tenis',
    residentName: 'María García',
    startTime: new Date(currentYear, currentMonth, 26, 17, 0),
    endTime: new Date(currentYear, currentMonth, 26, 19, 0),
    status: 'approved',
    notes: 'Entrenamiento',
  },
  {
    id: 'res-23',
    spaceId: 'space-1',
    spaceName: 'Salón Social',
    residentName: 'Juan Pérez',
    startTime: new Date(currentYear, currentMonth, 27, 18, 0),
    endTime: new Date(currentYear, currentMonth, 27, 22, 0),
    status: 'approved',
    notes: 'Aniversario',
  },
  {
    id: 'res-24',
    spaceId: 'space-2',
    spaceName: 'Área de BBQ',
    residentName: 'Carlos López',
    startTime: new Date(currentYear, currentMonth, 26, 13, 0),
    endTime: new Date(currentYear, currentMonth, 26, 17, 0),
    status: 'approved',
  },
  {
    id: 'res-25',
    spaceId: 'space-3',
    spaceName: 'Gimnasio',
    residentName: 'Laura Torres',
    startTime: new Date(currentYear, currentMonth, 27, 17, 0),
    endTime: new Date(currentYear, currentMonth, 27, 19, 0),
    status: 'approved',
  },
  {
    id: 'res-26',
    spaceId: 'space-4',
    spaceName: 'Piscina',
    residentName: 'Miguel Ramírez',
    startTime: new Date(currentYear, currentMonth, 25, 13, 0),
    endTime: new Date(currentYear, currentMonth, 25, 16, 0),
    status: 'approved',
  },
  {
    id: 'res-27',
    spaceId: 'space-5',
    spaceName: 'Cancha de Tenis',
    residentName: 'Patricia Morales',
    startTime: new Date(currentYear, currentMonth, 27, 15, 0),
    endTime: new Date(currentYear, currentMonth, 27, 17, 0),
    status: 'approved',
  },
  {
    id: 'res-28',
    spaceId: 'space-1',
    spaceName: 'Salón Social',
    residentName: 'Fernando García',
    startTime: new Date(currentYear, currentMonth, 29, 19, 0),
    endTime: new Date(currentYear, currentMonth, 29, 23, 0),
    status: 'pending',
  },
  {
    id: 'res-29',
    spaceId: 'space-2',
    spaceName: 'Área de BBQ',
    residentName: 'Valeria López',
    startTime: new Date(currentYear, currentMonth, 28, 12, 0),
    endTime: new Date(currentYear, currentMonth, 28, 16, 0),
    status: 'approved',
  },
  {
    id: 'res-30',
    spaceId: 'space-3',
    spaceName: 'Gimnasio',
    residentName: 'Diego Martínez',
    startTime: new Date(currentYear, currentMonth, 28, 7, 0),
    endTime: new Date(currentYear, currentMonth, 28, 9, 0),
    status: 'approved',
  },
  {
    id: 'res-31',
    spaceId: 'space-1',
    spaceName: 'Salón Social',
    residentName: 'Ana Martínez',
    startTime: new Date(currentYear, currentMonth, 25, 10, 0),
    endTime: new Date(currentYear, currentMonth, 25, 13, 0),
    status: 'approved',
    notes: 'Baby shower',
  },
  {
    id: 'res-32',
    spaceId: 'space-2',
    spaceName: 'Área de BBQ',
    residentName: 'Luis Rodríguez',
    startTime: new Date(currentYear, currentMonth, 29, 13, 0),
    endTime: new Date(currentYear, currentMonth, 29, 17, 0),
    status: 'approved',
  },
  {
    id: 'res-33',
    spaceId: 'space-4',
    spaceName: 'Piscina',
    residentName: 'Sofia Hernández',
    startTime: new Date(currentYear, currentMonth, 28, 10, 0),
    endTime: new Date(currentYear, currentMonth, 28, 13, 0),
    status: 'approved',
  },
  {
    id: 'res-34',
    spaceId: 'space-5',
    spaceName: 'Cancha de Tenis',
    residentName: 'Pedro Sánchez',
    startTime: new Date(currentYear, currentMonth, 28, 16, 0),
    endTime: new Date(currentYear, currentMonth, 28, 18, 0),
    status: 'approved',
  },
  {
    id: 'res-35',
    spaceId: 'space-3',
    spaceName: 'Gimnasio',
    residentName: 'Carmen Flores',
    startTime: new Date(currentYear, currentMonth, 29, 18, 0),
    endTime: new Date(currentYear, currentMonth, 29, 20, 0),
    status: 'approved',
  },
  {
    id: 'res-36',
    spaceId: 'space-1',
    spaceName: 'Salón Social',
    residentName: 'Roberto Castro',
    startTime: new Date(currentYear, currentMonth, 30, 18, 0),
    endTime: new Date(currentYear, currentMonth, 30, 22, 0),
    status: 'approved',
    notes: 'Fiesta de fin de año',
  },
  {
    id: 'res-37',
    spaceId: 'space-4',
    spaceName: 'Piscina',
    residentName: 'María García',
    startTime: new Date(currentYear, currentMonth, 30, 10, 0),
    endTime: new Date(currentYear, currentMonth, 30, 14, 0),
    status: 'approved',
  },
  {
    id: 'res-38',
    spaceId: 'space-2',
    spaceName: 'Área de BBQ',
    residentName: 'Juan Pérez',
    startTime: new Date(currentYear, currentMonth, 31, 12, 0),
    endTime: new Date(currentYear, currentMonth, 31, 16, 0),
    status: 'pending',
  },
  {
    id: 'res-39',
    spaceId: 'space-5',
    spaceName: 'Cancha de Tenis',
    residentName: 'Carlos López',
    startTime: new Date(currentYear, currentMonth, 29, 8, 0),
    endTime: new Date(currentYear, currentMonth, 29, 10, 0),
    status: 'approved',
  },
  {
    id: 'res-40',
    spaceId: 'space-3',
    spaceName: 'Gimnasio',
    residentName: 'Laura Torres',
    startTime: new Date(currentYear, currentMonth, 30, 6, 0),
    endTime: new Date(currentYear, currentMonth, 30, 8, 0),
    status: 'approved',
  },
];

export const MOCK_RESIDENTS: Resident[] = [
  {
    id: 'resident-1',
    name: 'María García López',
    unitNumber: 'Apto 101',
    phone: '6621-1234',
    email: 'maria.garcia@email.com',
  },
  {
    id: 'resident-2',
    name: 'Juan Pérez Martínez',
    unitNumber: 'Apto 102',
    phone: '6621-5678',
    email: 'juan.perez@email.com',
  },
  {
    id: 'resident-3',
    name: 'Carlos López Ramírez',
    unitNumber: 'Apto 103',
    phone: '6622-9012',
    email: 'carlos.lopez@email.com',
  },
  {
    id: 'resident-4',
    name: 'Ana Martínez Sánchez',
    unitNumber: 'Apto 201',
    phone: '6622-3456',
    email: 'ana.martinez@email.com',
  },
  {
    id: 'resident-5',
    name: 'Luis Rodríguez Castro',
    unitNumber: 'Apto 202',
    phone: '6623-7890',
    email: 'luis.rodriguez@email.com',
  },
  {
    id: 'resident-6',
    name: 'Sofia Hernández Morales',
    unitNumber: 'Apto 203',
    phone: '6623-1234',
    email: 'sofia.hernandez@email.com',
  },
  {
    id: 'resident-7',
    name: 'Pedro Sánchez Torres',
    unitNumber: 'Casa 12',
    phone: '6624-5678',
    email: 'pedro.sanchez@email.com',
  },
  {
    id: 'resident-8',
    name: 'Laura Torres Ruiz',
    unitNumber: 'Casa 13',
    phone: '6624-9012',
    email: 'laura.torres@email.com',
  },
  {
    id: 'resident-9',
    name: 'Miguel Ramírez Díaz',
    unitNumber: 'Casa 14',
    phone: '6625-3456',
    email: 'miguel.ramirez@email.com',
  },
  {
    id: 'resident-10',
    name: 'Carmen Flores Vega',
    unitNumber: 'Lote 8',
    phone: '6625-7890',
    email: 'carmen.flores@email.com',
  },
  {
    id: 'resident-11',
    name: 'Roberto Castro Méndez',
    unitNumber: 'Lote 9',
    phone: '6626-1234',
    email: 'roberto.castro@email.com',
  },
  {
    id: 'resident-12',
    name: 'Patricia Morales Silva',
    unitNumber: 'Lote 10',
    phone: '6626-5678',
    email: 'patricia.morales@email.com',
  },
  {
    id: 'resident-13',
    name: 'Fernando García Ruiz',
    unitNumber: 'Apto 301',
    phone: '6627-1234',
    email: 'fernando.garcia@email.com',
  },
  {
    id: 'resident-14',
    name: 'Valeria López González',
    unitNumber: 'Apto 302',
    phone: '6627-5678',
    email: 'valeria.lopez@email.com',
  },
  {
    id: 'resident-15',
    name: 'Diego Martínez Cruz',
    unitNumber: 'Apto 303',
    phone: '6628-9012',
    email: 'diego.martinez@email.com',
  },
];
