import { Delivery, Ticket, CheckItem } from './types';

export const MOCK_RESIDENCIALES = [
  { id: '1', name: 'Arcos Santa Maria I' },
  { id: '2', name: 'Arcos Santa Maria II' },
  { id: '3', name: 'Villa del Sol' },
  { id: '4', name: 'Las Colinas' },
  { id: '5', name: 'Jardines del Norte' },
  { id: '6', name: 'Costa Verde' },
];

export const MOCK_UNITS_BY_RESIDENCIAL: Record<string, string[]> = {
  '1': ['Apto 101', 'Apto 102', 'Apto 103', 'Apto 201', 'Apto 202', 'Apto 203'],
  '2': ['Apto 204', 'Apto 205', 'Apto 301', 'Apto 302', 'Apto 303', 'Apto 304'],
  '3': ['Casa 12', 'Casa 13', 'Casa 14', 'Casa 15', 'Casa 16', 'Casa 17', 'Casa 18'],
  '4': ['Lote 8', 'Lote 9', 'Lote 10', 'Apto 401', 'Apto 402', 'Apto 403'],
  '5': ['Apto 501', 'Apto 502', 'Apto 503', 'Apto 601', 'Apto 602', 'Apto 603'],
  '6': ['Apto 601', 'Apto 602', 'Apto 701', 'Apto 702', 'Apto 801', 'Apto 802'],
};

export const MOCK_RESIDENTS = [
  { id: 'res1', name: 'Juan Pérez García', phone: '6621-1234' },
  { id: 'res2', name: 'María González López', phone: '6621-5678' },
  { id: 'res3', name: 'Carlos López Ramírez', phone: '6622-9012' },
  { id: 'res4', name: 'Ana Martínez Sánchez', phone: '6622-3456' },
  { id: 'res5', name: 'Luis Rodríguez Castro', phone: '6623-7890' },
  { id: 'res6', name: 'Sofia Hernández Morales', phone: '6623-1234' },
  { id: 'res7', name: 'Pedro Sánchez Torres', phone: '6624-5678' },
  { id: 'res8', name: 'Laura Flores Ruiz', phone: '6624-9012' },
  { id: 'res9', name: 'Miguel Ramírez Díaz', phone: '6625-3456' },
  { id: 'res10', name: 'Carmen Flores Vega', phone: '6625-7890' },
  { id: 'res11', name: 'Roberto Castro Núñez', phone: '6626-1234' },
  { id: 'res12', name: 'Patricia Morales León', phone: '6626-5678' },
  { id: 'res13', name: 'Fernando Silva Ortiz', phone: '6621-2345' },
  { id: 'res14', name: 'Isabel Gutiérrez Ramos', phone: '6622-6789' },
  { id: 'res15', name: 'Jorge Mendoza Vargas', phone: '6623-4567' },
];

export const DEFAULT_CHECKLIST_ITEMS: Omit<CheckItem, 'id'>[] = [
  { label: 'Zócalos', status: null, observations: '' },
  { label: 'Gabinetes', status: null, observations: '' },
  { label: 'Pintura', status: null, observations: '' },
  { label: 'Puertas', status: null, observations: '' },
  { label: 'Tomas de corriente', status: null, observations: '' },
  { label: 'Presión de agua', status: null, observations: '' },
  { label: 'Agua caliente', status: null, observations: '' },
  { label: 'Agua fría', status: null, observations: '' },
];

export const MOCK_DELIVERIES: Delivery[] = [
  {
    id: 'del1',
    residencialId: '1',
    residencialName: 'Arcos Santa Maria I',
    unitNumber: 'Apto 101',
    residentId: 'res1',
    residentName: 'Juan Pérez García',
    deliveryDate: new Date(2024, 10, 15, 10, 0).toISOString(),
    checklistItems: [
      { id: 'ci1', label: 'Zócalos', status: 'compliant', observations: '' },
      { id: 'ci2', label: 'Gabinetes', status: 'compliant', observations: '' },
      { id: 'ci3', label: 'Pintura', status: 'with_observations', observations: 'Requiere retoque en pared principal' },
      { id: 'ci4', label: 'Puertas', status: 'compliant', observations: '' },
      { id: 'ci5', label: 'Tomas de corriente', status: 'compliant', observations: '' },
      { id: 'ci6', label: 'Presión de agua', status: 'compliant', observations: '' },
      { id: 'ci7', label: 'Agua caliente', status: 'non_compliant', observations: 'No funciona calentador' },
      { id: 'ci8', label: 'Agua fría', status: 'compliant', observations: '' },
    ],
    photos: [
      { id: 'p1', name: 'sala.jpg', url: '/mock/sala.jpg', uploadedAt: new Date(2024, 10, 15, 10, 15).toISOString() },
      { id: 'p2', name: 'cocina.jpg', url: '/mock/cocina.jpg', uploadedAt: new Date(2024, 10, 15, 10, 16).toISOString() },
    ],
    signature: 'data:image/png;base64,mock-signature',
    generalObservations: 'Cliente satisfecho en general, pendientes menores por resolver',
    ticketId: 'TCK-001',
    status: 'with_issues',
    createdAt: new Date(2024, 10, 15, 10, 0).toISOString(),
    createdBy: 'Admin Usuario',
  },
  {
    id: 'del2',
    residencialId: '3',
    residencialName: 'Villa del Sol',
    unitNumber: 'Casa 12',
    residentId: 'res5',
    residentName: 'Luis Rodríguez Castro',
    deliveryDate: new Date(2024, 10, 18, 14, 0).toISOString(),
    checklistItems: [
      { id: 'ci9', label: 'Zócalos', status: 'compliant', observations: '' },
      { id: 'ci10', label: 'Gabinetes', status: 'compliant', observations: '' },
      { id: 'ci11', label: 'Pintura', status: 'compliant', observations: '' },
      { id: 'ci12', label: 'Puertas', status: 'compliant', observations: '' },
      { id: 'ci13', label: 'Tomas de corriente', status: 'compliant', observations: '' },
      { id: 'ci14', label: 'Presión de agua', status: 'compliant', observations: '' },
      { id: 'ci15', label: 'Agua caliente', status: 'compliant', observations: '' },
      { id: 'ci16', label: 'Agua fría', status: 'compliant', observations: '' },
    ],
    photos: [
      { id: 'p3', name: 'exterior.jpg', url: '/mock/exterior.jpg', uploadedAt: new Date(2024, 10, 18, 14, 20).toISOString() },
    ],
    signature: 'data:image/png;base64,mock-signature-2',
    generalObservations: 'Entrega sin observaciones, todo conforme',
    status: 'completed',
    createdAt: new Date(2024, 10, 18, 14, 0).toISOString(),
    createdBy: 'Admin Usuario',
  },
  {
    id: 'del3',
    residencialId: '2',
    residencialName: 'Arcos Santa Maria II',
    unitNumber: 'Apto 205',
    residentId: 'res3',
    residentName: 'Carlos López Ramírez',
    deliveryDate: new Date(2024, 10, 20, 9, 30).toISOString(),
    checklistItems: [
      { id: 'ci17', label: 'Zócalos', status: 'compliant', observations: '' },
      { id: 'ci18', label: 'Gabinetes', status: 'non_compliant', observations: 'Puerta de gabinete suelta' },
      { id: 'ci19', label: 'Pintura', status: 'compliant', observations: '' },
      { id: 'ci20', label: 'Puertas', status: 'with_observations', observations: 'Puerta principal roza el marco' },
      { id: 'ci21', label: 'Tomas de corriente', status: 'compliant', observations: '' },
      { id: 'ci22', label: 'Presión de agua', status: 'compliant', observations: '' },
      { id: 'ci23', label: 'Agua caliente', status: 'compliant', observations: '' },
      { id: 'ci24', label: 'Agua fría', status: 'compliant', observations: '' },
    ],
    photos: [],
    signature: 'data:image/png;base64,mock-signature-3',
    generalObservations: 'Requiere atención en gabinetes y puerta principal',
    ticketId: 'TCK-002',
    status: 'with_issues',
    createdAt: new Date(2024, 10, 20, 9, 30).toISOString(),
    createdBy: 'Admin Usuario',
  },
];

export const MOCK_TICKETS: Ticket[] = [
  {
    id: 'TCK-001',
    deliveryId: 'del1',
    unitNumber: 'Apto 101',
    residencialName: 'Arcos Santa Maria I',
    residentName: 'Juan Pérez García',
    status: 'in_progress',
    priority: 'high',
    pendingItems: [
      'Retoque en pared principal',
      'Reparación de calentador de agua',
    ],
    createdAt: new Date(2024, 10, 15, 10, 30).toISOString(),
  },
  {
    id: 'TCK-002',
    deliveryId: 'del3',
    unitNumber: 'Apto 205',
    residencialName: 'Arcos Santa Maria II',
    residentName: 'Carlos López Ramírez',
    status: 'open',
    priority: 'medium',
    pendingItems: [
      'Ajuste de puerta de gabinete',
      'Ajuste de puerta principal',
    ],
    createdAt: new Date(2024, 10, 20, 9, 45).toISOString(),
  },
];
